apiVersion: v1
kind: Service
metadata:
  labels:
    app: refredis
  name: refredis
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: redis
  selector:
    app: refredis
  sessionAffinity: None
  type: ClusterIP

