apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: metricbeat-daemonset
      - podSelector:
          matchLabels:
            app: {{ .Release.Name }}
      - podSelector:
          matchLabels:
            app: refredis   
      - namespaceSelector: {}
      ports:
        - port: 9568
          protocol: TCP    