apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app:  {{ .Release.Name }}
    role: ngcp-service
  name:  {{ .Release.Name }}
spec:
  serviceName: "{{ .Release.Name }}-cluster"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app:  {{ .Release.Name }}
  template:
    metadata:
      labels:
        app:  {{ .Release.Name }}
        role: ngcp-service
    spec:
      affinity: {}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.registry }}/ngcp/rakv:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
          - containerPort: 4000
          volumeMounts:
            - name: rakv-data
              mountPath: /app/rakvdata
          env:
            - name: DEBUG
              value: {{ .Values.containers.env.debug | quote }}
            {{- if .Values.containers.env.jaeger.enabled }}
            - name: OC_JAEGER_HOST
              value: "jaeger-agent"
            - name: OC_SAMPLING_RATE
              value: {{ .Values.containers.env.traceSampling | quote }}
            {{- end }}
            - name: K8S_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_SERVICE_NAME
              value: "{{ .Release.Name }}-cluster"
            - name: K8S_HOSTNAME_SUFFIX
              value: .$(K8S_SERVICE_NAME).$(K8S_NAMESPACE).svc.cluster.local
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DOCKER_IMAGE
              value: "{{ .Values.image.registry}}/ngcp/rakv:{{ .Values.image.tag }}"
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 6
            httpGet:
              path: /startupcheck
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            initialDelaySeconds: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}          
      securityContext:
        runAsGroup: 10001
        runAsUser: 10001
        supplementalGroups: []
        fsGroup: 20001
  volumeClaimTemplates:                     
  - metadata:
      name: rakv-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi