apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-cluster
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 80
  selector:
    app: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP

