apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rakv
    role: ngcp-service
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rakv
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rakv
        role: ngcp-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9568"
        prometheus.io/path: "/metrics"
    spec:
      affinity: {}
      containers:
        - env:
            - name: DEBUG
              value: {{ .Values.containers.env.debug | quote }}  
            {{- if .Values.containers.env.jaeger.enabled }}
            - name: OC_JAEGER_HOST
              value: "jaeger-agent"
            - name: OC_SAMPLING_RATE
              value: {{ .Values.containers.env.traceSampling | quote }}
            {{- end }}
            - name: K8S_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_SERVICE_NAME
              value: "{{ .Release.Name }}-cluster"
            - name: K8S_HOSTNAME_SUFFIX
              value: .$(K8S_SERVICE_NAME).$(K8S_NAMESPACE).svc.cluster.local
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MAX_COMMANDS
              value: "{{ .Values.params.maxcommands }}"
            - name: TIME_BETWEEN_COMMANDS
              value: "{{ .Values.params.timebetweencommands }}"
            - name: MAX_KILLS
              value: "{{ .Values.params.maxkills }}"
            - name: TIME_BETWEEN_KILLS
              value: "{{ .Values.params.timebetweenkills }}"
            - name: DOCKER_IMAGE
              value: "{{ .Values.image.registry}}/ngcp/rakvclient:{{ .Values.image.tag }}"
          image: "{{ .Values.image.registry }}/ngcp/rakvclient:{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Release.Name }}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}  
      # dnsPolicy: ClusterFirst
      # restartPolicy: Always
      # schedulerName: default-scheduler
      securityContext:
        runAsGroup: 10001
        runAsUser: 10001
        supplementalGroups: []
        fsGroup: 20001
      # terminationGracePeriodSeconds: 30